---
title: "Reticulate"
author: ''
date: '2022-02-09'
tags:
- python
- R
---


```{r setup,inclue=F,results = FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(comment = NULL )
library(reticulate)
knitr::knit_engines$set(python = reticulate::eng_python)
knitr::opts_chunk$set(python.reticulate = TRUE)

```

```{r,inclue=F,results = FALSE}
library(tidyverse)
require(ggplot2)
library(ggfortify)
library(kableExtra)
library(xts)
library(gridExtra)
library(ggResidpanel)
library(grid)
data("mpg")
dt<-subset(mpg, drv !="f")
ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(color = class)) +
  geom_smooth(se = FALSE) +
  labs(title = "Fuel efficiency generally decreases with engine size")

```
```{python,inclue=F,results = FALSE}
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

url = 'https://raw.githubusercontent.com/NicJC/UFC/main/ufc.csv'
data = pd.read_csv(url)
data.count()
dt = data.head(20)
x = dt['Height']
y = dt['Weight']

fig, ax = plt.subplots()
ax.barh(x, y)

plt.style.use('bmh')

plt.title('UFC Fighter's Weight by Height')
plt.show()

```


```{r}
library(gplots)
heatmap.2(t(iris[, 1:4]), trace="none", scale="row", key=TRUE, mar=c(2, 8), cexRow=1, ColSideColors=c("grey", "black", "yellow")[iris$Species])
```





```{python}

url = 'https://raw.githubusercontent.com/NicJC/Gun-Violence/main/gun.csv'
data = pd.read_csv(url)
data.head()
data.count()

dt = data.head(40)

plt.figure(figsize=(25, 25))
sns.pairplot(dt,hue='State')
plt.show()
```

